---
title: Nerdlab
timezone: UTC
collections:
  agenda:
    title: Agenda
    output: false
  cta:
    title: CTA
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: Agenda
  values:
    title: 
- scope:
    path: ''
    type: CTA
  values:
    title: 
permalink: pretty
markdown: kramdown
exclude:
- Gem*
- "*.lock"
- "*rb"
- ".git*"
- "*.md"
- "*.json"
- node_modules
- vendor
- gulp*
- ".jekyll-metadata"
- ".*"
author: Nerdlab
description: Nerdlab is een open collectief van makers. We bouwen installaties en
  machines, organiseren evenementen en veroveren de wereld. Oh, en daarnaast hebben
  we ook een fablab in Gent waar iedereen welkom is.
url: http://nerdlab.be/
labels:
  copyright-year: 2017
  copyright-author: Nerdlab
social:
  twitter_image: 
  facebook_image: 
  twitter_username: 
  facebook_username: 
  instagram_username: 
  youtube_username: 
google_analytics: 
navigation:
- title: Lab
  url: lab/
- title: Projecten
  url: projecten/
- title: Agenda
  url: agenda/
- title: Kom langs
  url: word-nerd/
