---
title: Nerdlab
timezone: UTC
collections:
  agenda:
    title: Agenda
    output: false
  cta:
    title: CTA
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: Agenda
  values:
    title: 
- scope:
    path: ''
    type: CTA
  values:
    title: 
permalink: pretty
markdown: kramdown
exclude:
- Gem*
- "*.lock"
- "*rb"
- ".git*"
- "*.md"
- "*.json"
- node_modules
- vendor
- gulp*
- ".jekyll-metadata"
- ".*"
url: http://nerdlab.be/
google_analytics: UA-48840590-1
author: Nerdlab
description: Nerdlab is een open collectief van makers. We bouwen installaties en
  machines, organiseren evenementen en veroveren de wereld. Oh, en daarnaast hebben
  we ook een lab in Gent waar iedereen welkom is.
navigation:
- title: Agenda
  url: agenda/
- title: Ons Lab
  url: lab/
- title: Onze projecten
  url: projecten/
- title: Contact
  url: word-nerd/
labels:
  copyright-year: 2017
  copyright-author: Nerdlab
Info:
  Naam: Nerdlab
  Straat: Nieuwland
  Nummer: 67
  Postcode: 9000
  Plaats: Gent
  Email: info@nerdlab.be
Social:
  Titel: 'Volg ons:'
  Twitter link: https://twitter.com/NerdLab9000
  Facebook link: https://www.facebook.com/Nerdlab
  Instagram link: https://www.instagram.com/nerdlab9000
Newsletter:
  Intro: Laat hier je mailadres achter zodat we je af en toe nieuws over Nerdlab kunnen
    sturen.
  Placeholder: naam@voorbeeld.com
  Button label: Schrijf in
